---
all:
  children:
    keepalived_hosts:
      hosts:
        lb1:
          ansible_host: "192.168.100.171"
          ansible_private_key_file: "ssh/work_test_key"
        lb2:
          ansible_host: "192.168.100.172"
          ansible_private_key_file: "ssh/work_test_key"
    nginx:
      hosts:
        nginx1:
          ansible_host: "192.168.100.173"
          ansible_private_key_file: "ssh/work_test_key"
        nginx2:
          ansible_host: "192.168.100.174"
          ansible_private_key_file: "ssh/work_test_key"
        nginx3:
          ansible_host: "192.168.100.175"
          ansible_private_key_file: "ssh/work_test_key"
    mysql:
      hosts:
        mysql:
          ansible_host: "192.168.100.176"
          ansible_private_key_file: "ssh/work_test_key"
    ansible:
      hosts:
        ansible:
          ansible_host: "192.168.100.177"
          ansible_private_key_file: "ssh/work_test_key"

...
